### PR TITLE
missing step due to missing stemcell warning

### PR DESCRIPTION
**Pull request by ymeillier**
Will need to add screenshot too.

### CODE REVIEW

**Comment by afewellvmware** [comment]
Thank you @ymeillier for reporting this ... I have only ran into missing stemcell or need to manually import stemcell during upgrade operations but I havent run into it doing new install. I am going to hold this pr open for a bit while I investigate further

**Comment by natereid72** [comment]
@ymeillier , can you confirm which lab template and location you are running when you encounter this? (e.g v11/v10, sandbox geo/VLP).

The NASA and VLP look like they have the correct versions of everything for manual install of PKS.

**Comment by ymeillier** [comment]
Hi Nate

Org: SDDC Sandbox (https://vcore5-us01.oc.vmware.com)
Lab/vApp: CNABU-PKS-Ninja-v11-NsxtInstalled
[cid:image001.png@01D4C821.3D685270]

-y

Yannick Meillier
NSX Solutions Architect
ymeillier@vmware.com<mailto:ymeillier@vmware.com>
380 Interlocken Blvd, Suite 500, Broomfield, CO 80021
303.305.6359 Office
720.382.4511 Mobile
303.942.4601 Fax


[VMware]<http://www.vmware.com/>

**Comment by natereid72** [comment]
Which stemcell version was installed when it said it needed to be updated?

**Comment by ymeillier** [comment]
It is the one that the PKS tile references at the bottom in the tile when the warning about missing stemcells shows up. 170.15.
The stemcell file is actually on the download folder in the lab E; Drive.
[cid:image001.png@01D4C850.7DF53DB0]
One just needs to go to the library and point PKS to it.


Yannick Meillier
NSX Solutions Architect
ymeillier@vmware.com<mailto:ymeillier@vmware.com>
380 Interlocken Blvd, Suite 500, Broomfield, CO 80021
303.305.6359 Office
720.382.4511 Mobile
303.942.4601 Fax


[VMware]<http://www.vmware.com/>

**Comment by natereid72** [comment]
ok, weird. should only need to do that if upgrading (as Art mentioned)

**Comment by natereid72** [comment]
ok, finalyl had time to confirm. so, something definitely changed between lab template v10/v11 and pks 1.2/1.3 with opsman ova deploy and pks import. 

@ymeillier Do you want to update screenshot on this same PR with another commit?

**Comment by ymeillier** [comment]
I could but it seems that I am unable upload images to the folder.
Unless I am not following the right process…
[cid:image001.png@01D4C89C.2678A080]

Yannick Meillier
NSX Solutions Architect
ymeillier@vmware.com<mailto:ymeillier@vmware.com>
380 Interlocken Blvd, Suite 500, Broomfield, CO 80021
303.305.6359 Office
720.382.4511 Mobile
303.942.4601 Fax


[VMware]<http://www.vmware.com/>

**Comment by natereid72** [comment]
It's just like updating a readme file. The image is another file. But you would want to be running from a git directory structure on your workstation that you have cloned. If you're just adding PR by editing from github, it's not going to be as easy. 

It's a good exercise to go through and Art has a guide for it on the repo. But don't make it a priority if you don't have cycles.

**Pull request merged**
